# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw99T-I9jLtHDzHXn0ys6mvZFWAUn638
"""

!pip install -q streamlit

!npm install localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# 
# st.set_page_config(page_title="Cybersecurity Toolkit")
# 
# st.title("Online Banking Cybersecurity Awareness Toolkit")
# 
# df = pd.read_csv("Online_Banking_Cleaned_Dataset.csv")
# 
# page = st.sidebar.selectbox(
#     "Menu",
#     [
#         "Home",
#         "Dataset",
#         "EDA",
#         "Prediction",
#         "Learning Centre"
#     ]
# )
# 
# if page=="Home":
# 
#     st.header("Welcome")
# 
#     st.write("""
#     This toolkit is based on survey findings.
#     """)
# 
# elif page=="Dataset":
# 
#     st.header("Dataset")
# 
#     st.write(df.head())
# 
#     st.write(df.shape)
# 
# elif page=="EDA":
# 
#     st.header("Age Distribution")
# 
#     st.bar_chart(df["Age"].value_counts())
# 
# elif page=="Prediction":
# 
#     st.header("Cybersecurity Awareness")
# 
#     phishing = st.selectbox(
#         "Can you recognise phishing emails?",
#         ["Yes","Sometimes","No"]
#     )
# 
#     otp = st.selectbox(
#         "Would you share your OTP?",
#         ["No","Not Sure","Yes"]
#     )
# 
#     score = 0
# 
#     if phishing=="Yes":
#         score+=1
# 
#     if otp=="No":
#         score+=1
# 
#     if st.button("Predict"):
# 
#         if score==2:
# 
#             st.success("High Awareness")
# 
#         elif score==1:
# 
#             st.warning("Moderate Awareness")
# 
#         else:
# 
#             st.error("Low Awareness")
# 
# elif page=="Learning Centre":
# 
#     st.header("Cybersecurity Tips")
# 
#     st.markdown("""
#     ✅ Never share OTPs
# 
#     ✅ Enable MFA
# 
#     ✅ Verify banking websites
# 
#     ✅ Avoid public Wi-Fi
# 
#     ✅ Update banking apps regularly
#     """)

!streamlit run app.py &>/content/logs.txt &

!npx localtunnel --port 8501

