{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOpKouoOkRqMiShDo79SlH1",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Shavindri/Final-Year-Project/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "iaPP8pDLhhVD"
      },
      "outputs": [],
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "import os\n",
        "\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.ensemble import RandomForestRegressor\n",
        "from sklearn.metrics import mean_absolute_error, r2_score\n",
        "\n",
        "st.set_page_config(\n",
        "    page_title=\"Online Banking Cybersecurity Awareness Toolkit\",\n",
        "    layout=\"wide\"\n",
        ")\n",
        "\n",
        "@st.cache_data\n",
        "def load_data():\n",
        "    return pd.read_csv(\"Online_Banking_Cleaned_Dataset.csv\")\n",
        "\n",
        "df = load_data()\n",
        "\n",
        "st.sidebar.title(\"Navigation\")\n",
        "\n",
        "page = st.sidebar.radio(\n",
        "    \"Go to\",\n",
        "    [\n",
        "        \"Home\",\n",
        "        \"Dataset Overview\",\n",
        "        \"Exploratory Data Analysis\",\n",
        "        \"Cyber Awareness Assessment\",\n",
        "        \"Biometric Training Demo\",\n",
        "        \"Learning Resources\"\n",
        "    ]\n",
        ")\n",
        "if page == \"Home\":\n",
        "\n",
        "    st.title(\"Online Banking Cybersecurity Awareness Toolkit\")\n",
        "\n",
        "    st.markdown(\"\"\"\n",
        "    ### Evaluating the Effectiveness of User Awareness and Front-End Security Measures in Online Banking\n",
        "    \"\"\")\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    col1, col2 = st.columns([2,1])\n",
        "\n",
        "    with col1:\n",
        "\n",
        "        st.write(\"\"\"\n",
        "        Welcome to the Online Banking Cybersecurity Awareness Toolkit.\n",
        "\n",
        "        This application was developed as part of a Final Year Research Project to\n",
        "        evaluate users' cybersecurity awareness and the effectiveness of front-end\n",
        "        security measures used in online banking.\n",
        "\n",
        "        The toolkit combines survey findings, exploratory data analysis,\n",
        "        cybersecurity awareness assessment, personalised recommendations,\n",
        "        and an educational biometric authentication demonstration.\n",
        "        \"\"\")\n",
        "\n",
        "    with col2:\n",
        "\n",
        "        st.metric(\"Survey Responses\", \"32\")\n",
        "        st.metric(\"Questionnaire Items\", \"41\")\n",
        "        st.metric(\"Toolkit Modules\", \"5\")\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    st.subheader(\"Toolkit Features\")\n",
        "\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "\n",
        "        st.success(\"Cyber Awareness Assessment\")\n",
        "\n",
        "        st.write(\"\"\"\n",
        "        • Assess users' cybersecurity awareness\n",
        "\n",
        "        • Calculate awareness percentage\n",
        "\n",
        "        • Provide personalised recommendations\n",
        "        \"\"\")\n",
        "\n",
        "        st.success(\"Exploratory Data Analysis\")\n",
        "\n",
        "        st.write(\"\"\"\n",
        "        • Interactive charts\n",
        "\n",
        "        • Dataset overview\n",
        "\n",
        "        • Correlation analysis\n",
        "        \"\"\")\n",
        "\n",
        "    with col2:\n",
        "\n",
        "        st.success(\"Biometric Training Demonstration\")\n",
        "\n",
        "        st.write(\"\"\"\n",
        "        • Face detection explanation\n",
        "\n",
        "        • Facial landmark identification\n",
        "\n",
        "        • Faceprint generation concept\n",
        "        \"\"\")\n",
        "\n",
        "        st.success(\"Learning Resources\")\n",
        "\n",
        "        st.write(\"\"\"\n",
        "        • Phishing awareness\n",
        "\n",
        "        • Password security\n",
        "\n",
        "        • Multi-Factor Authentication\n",
        "\n",
        "        • AI-enabled cyber threats\n",
        "        \"\"\")\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    with st.expander(\"Project Aim\"):\n",
        "\n",
        "        st.write(\"\"\"\n",
        "        To evaluate the effectiveness of user awareness and front-end security\n",
        "        measures in online banking and to develop an interactive educational\n",
        "        toolkit that improves users' cybersecurity knowledge and promotes safer\n",
        "        online banking practices.\n",
        "        \"\"\")\n",
        "\n",
        "    with st.expander(\"How to Use This Toolkit\"):\n",
        "\n",
        "        st.write(\"\"\"\n",
        "        1. Review the dataset overview.\n",
        "\n",
        "        2. Explore the visualisations.\n",
        "\n",
        "        3. Complete the Cyber Awareness Assessment.\n",
        "\n",
        "        4. Read your personalised recommendations.\n",
        "\n",
        "        5. Learn how biometric authentication works through the training demonstration.\n",
        "        \"\"\")\n",
        "\n",
        "\n",
        "elif page == \"Dataset Overview\":\n",
        "    st.title(\"Dataset Overview\")\n",
        "\n",
        "    st.subheader(\"Dataset Shape\")\n",
        "    st.write(\"Rows:\", df.shape[0])\n",
        "    st.write(\"Columns:\", df.shape[1])\n",
        "\n",
        "    st.subheader(\"Dataset Preview\")\n",
        "    st.dataframe(df.head())\n",
        "\n",
        "    st.subheader(\"Missing Values\")\n",
        "    st.dataframe(df.isnull().sum())\n",
        "\n",
        "    st.subheader(\"Data Types\")\n",
        "    st.dataframe(df.dtypes)\n",
        "\n",
        "\n",
        "elif page == \"Exploratory Data Analysis\":\n",
        "    st.title(\"Exploratory Data Analysis\")\n",
        "\n",
        "    option = st.selectbox(\n",
        "        \"Select Analysis\",\n",
        "        [\n",
        "            \"Age Distribution\",\n",
        "            \"Gender Distribution\",\n",
        "            \"Banking Usage\",\n",
        "            \"Platform Usage\",\n",
        "            \"Awareness Level\",\n",
        "            \"Behaviour Level\",\n",
        "            \"Biometric Level\",\n",
        "            \"Correlation Heatmap\"\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    if option == \"Age Distribution\":\n",
        "        st.bar_chart(df[\"Age\"].value_counts())\n",
        "\n",
        "    elif option == \"Gender Distribution\":\n",
        "        st.bar_chart(df[\"Gender\"].value_counts())\n",
        "\n",
        "    elif option == \"Banking Usage\":\n",
        "        st.bar_chart(df[\"Banking_Use\"].value_counts())\n",
        "\n",
        "    elif option == \"Platform Usage\":\n",
        "        st.bar_chart(df[\"Platform\"].value_counts())\n",
        "\n",
        "    elif option == \"Awareness Level\":\n",
        "        st.bar_chart(df[\"Awareness_Level\"].value_counts())\n",
        "\n",
        "    elif option == \"Behaviour Level\":\n",
        "        st.bar_chart(df[\"Behaviour_Level\"].value_counts())\n",
        "\n",
        "    elif option == \"Biometric Level\":\n",
        "        st.bar_chart(df[\"Biometric_Level\"].value_counts())\n",
        "\n",
        "    elif option == \"Correlation Heatmap\":\n",
        "        corr_cols = [\n",
        "            \"Awareness_Score\",\n",
        "            \"Opinion_Score\",\n",
        "            \"Behaviour_Score\",\n",
        "            \"Biometric_Score\"\n",
        "        ]\n",
        "\n",
        "        corr = df[corr_cols].corr()\n",
        "\n",
        "        fig, ax = plt.subplots(figsize=(7, 5))\n",
        "        sns.heatmap(corr, annot=True, cmap=\"Blues\", ax=ax)\n",
        "        st.pyplot(fig)\n",
        "\n",
        "\n",
        "elif page == \"Cyber Awareness Assessment\":\n",
        "    st.title(\"Cyber Awareness Assessment\")\n",
        "\n",
        "    st.write(\"\"\"\n",
        "    Answer the following questions. The application will calculate your cyber awareness score\n",
        "    and provide personalised feedback.\n",
        "    \"\"\")\n",
        "\n",
        "    score = 0\n",
        "    total = 8\n",
        "    feedback = []\n",
        "\n",
        "    phishing = st.selectbox(\n",
        "        \"1. What would you do if you received an email claiming your bank account will be suspended unless you click a link?\",\n",
        "        [\n",
        "            \"Verify the request using the bank's official website or customer service\",\n",
        "            \"Ignore it completely\",\n",
        "            \"Click the link immediately\"\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    if phishing == \"Verify the request using the bank's official website or customer service\":\n",
        "        score += 1\n",
        "    else:\n",
        "        feedback.append(\"Improve phishing awareness by verifying suspicious emails through official bank channels.\")\n",
        "\n",
        "    otp = st.selectbox(\n",
        "        \"2. What would you do if someone claiming to be from your bank asks for your OTP?\",\n",
        "        [\n",
        "            \"End the call and contact the bank through official channels\",\n",
        "            \"Ask why it is needed\",\n",
        "            \"Ignore the request but continue the conversation\",\n",
        "            \"Share the OTP\"\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    if otp == \"End the call and contact the bank through official channels\":\n",
        "        score += 1\n",
        "    else:\n",
        "        feedback.append(\"Never share OTPs. Banks will not ask customers to share OTPs, passwords, or PINs.\")\n",
        "\n",
        "    password = st.selectbox(\n",
        "        \"3. How often do you use a unique password for online banking?\",\n",
        "        [\"Always\", \"Sometimes\", \"Rarely\", \"Never\"]\n",
        "    )\n",
        "\n",
        "    if password == \"Always\":\n",
        "        score += 1\n",
        "    else:\n",
        "        feedback.append(\"Improve password practices by using a strong and unique password for online banking.\")\n",
        "\n",
        "    mfa = st.selectbox(\n",
        "        \"4. How often do you enable Multi-Factor Authentication when it is available?\",\n",
        "        [\"Always\", \"Sometimes\", \"Rarely\", \"Never\"]\n",
        "    )\n",
        "\n",
        "    if mfa == \"Always\":\n",
        "        score += 1\n",
        "    else:\n",
        "        feedback.append(\"Enable Multi-Factor Authentication to add an extra layer of protection.\")\n",
        "\n",
        "    website = st.selectbox(\n",
        "        \"5. How often do you verify the banking website before entering login details?\",\n",
        "        [\"Always\", \"Sometimes\", \"Rarely\", \"Never\"]\n",
        "    )\n",
        "\n",
        "    if website == \"Always\":\n",
        "        score += 1\n",
        "    else:\n",
        "        feedback.append(\"Always check website authenticity before entering banking credentials.\")\n",
        "\n",
        "    public_wifi = st.selectbox(\n",
        "        \"6. Would you use public Wi-Fi for online banking?\",\n",
        "        [\"Never\", \"Sometimes\", \"Often\"]\n",
        "    )\n",
        "\n",
        "    if public_wifi == \"Never\":\n",
        "        score += 1\n",
        "    else:\n",
        "        feedback.append(\"Avoid public Wi-Fi for online banking because it may expose sensitive information.\")\n",
        "\n",
        "    biometric = st.selectbox(\n",
        "        \"7. Do you understand how biometric authentication protects online banking accounts?\",\n",
        "        [\"Yes\", \"Somewhat\", \"No\"]\n",
        "    )\n",
        "\n",
        "    if biometric == \"Yes\":\n",
        "        score += 1\n",
        "    else:\n",
        "        feedback.append(\"Improve understanding of biometric authentication and how biometric data is protected.\")\n",
        "\n",
        "    ai_scams = st.selectbox(\n",
        "        \"8. What would you do if you received a voice call that sounded like your bank manager asking you to approve a transaction?\",\n",
        "        [\n",
        "            \"Verify the request using the bank's official contact details\",\n",
        "            \"End the call without checking\",\n",
        "            \"Approve the transaction\"\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    if ai_scams == \"Verify the request using the bank's official contact details\":\n",
        "        score += 1\n",
        "    else:\n",
        "        feedback.append(\"Be cautious of AI-generated scams and deepfake calls. Always verify urgent requests officially.\")\n",
        "\n",
        "    if st.button(\"Calculate Awareness Score\"):\n",
        "        percentage = round((score / total) * 100, 2)\n",
        "\n",
        "        st.subheader(\"Your Cyber Awareness Score\")\n",
        "        st.write(f\"{percentage}%\")\n",
        "\n",
        "        if percentage >= 75:\n",
        "            st.success(\"Awareness Level: High\")\n",
        "        elif percentage >= 50:\n",
        "            st.warning(\"Awareness Level: Moderate\")\n",
        "        else:\n",
        "            st.error(\"Awareness Level: Low\")\n",
        "\n",
        "        st.subheader(\"Personalised Feedback\")\n",
        "\n",
        "        if feedback:\n",
        "            for item in feedback:\n",
        "                st.write(\"- \" + item)\n",
        "        else:\n",
        "            st.write(\"You demonstrated strong cyber awareness across all assessed areas.\")\n",
        "\n",
        "\n",
        "elif page == \"Biometric Training Demo\":\n",
        "    st.title(\"Biometric Facial Identification Training Demonstration\")\n",
        "\n",
        "    st.write(\"\"\"\n",
        "    This section explains how biometric facial identification works in a simplified way.\n",
        "    It is not a real authentication system and does not store or verify biometric data.\n",
        "    \"\"\")\n",
        "\n",
        "    uploaded_image = st.file_uploader(\n",
        "        \"Upload a face image for demonstration purposes\",\n",
        "        type=[\"jpg\", \"jpeg\", \"png\"]\n",
        "    )\n",
        "\n",
        "    if uploaded_image is not None:\n",
        "        st.image(uploaded_image, caption=\"Uploaded Image\", use_container_width=True)\n",
        "\n",
        "        st.subheader(\"Step 1: Face Detection\")\n",
        "        st.write(\"\"\"\n",
        "        A biometric system first detects whether a face is present in the image.\n",
        "        \"\"\")\n",
        "\n",
        "        st.subheader(\"Step 2: Facial Landmark Identification\")\n",
        "        st.write(\"\"\"\n",
        "        The system identifies key facial landmarks such as the eyes, nose, mouth, jawline,\n",
        "        and distance between facial features.\n",
        "        \"\"\")\n",
        "\n",
        "        st.subheader(\"Step 3: Faceprint Generation\")\n",
        "        st.write(\"\"\"\n",
        "        These facial measurements are converted into a mathematical representation known as a faceprint.\n",
        "        A faceprint is not the same as a normal image; it is a numerical pattern used for comparison.\n",
        "        \"\"\")\n",
        "\n",
        "        st.subheader(\"Step 4: Matching Process\")\n",
        "        st.write(\"\"\"\n",
        "        In a real authentication system, the generated faceprint would be compared with a stored template\n",
        "        to decide whether access should be granted.\n",
        "        \"\"\")\n",
        "\n",
        "        st.warning(\"\"\"\n",
        "        This demonstration is educational only. It does not authenticate users, store biometric data,\n",
        "        or perform real facial recognition.\n",
        "        \"\"\")\n",
        "\n",
        "        st.subheader(\"Privacy and Security Considerations\")\n",
        "        st.write(\"\"\"\n",
        "        Biometric systems must protect user privacy by securely storing biometric templates,\n",
        "        limiting access to sensitive data, and clearly explaining how biometric information is used.\n",
        "        \"\"\")\n",
        "\n",
        "\n",
        "elif page == \"Learning Resources\":\n",
        "    st.title(\"Learning Resources\")\n",
        "\n",
        "    topic = st.selectbox(\n",
        "        \"Choose a topic\",\n",
        "        [\n",
        "            \"Phishing Awareness\",\n",
        "            \"OTP Security\",\n",
        "            \"Password Security\",\n",
        "            \"Multi-Factor Authentication\",\n",
        "            \"Safe Online Banking Behaviour\",\n",
        "            \"Biometric Authentication\",\n",
        "            \"AI Scams and Deepfake Fraud\"\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    if topic == \"Phishing Awareness\":\n",
        "        st.write(\"\"\"\n",
        "        Phishing is a method used by cybercriminals to trick users into revealing sensitive information.\n",
        "        Users should avoid clicking suspicious links and should verify messages through official bank channels.\n",
        "        \"\"\")\n",
        "\n",
        "    elif topic == \"OTP Security\":\n",
        "        st.write(\"\"\"\n",
        "        OTPs should never be shared with anyone. Legitimate banks do not ask customers to reveal OTPs,\n",
        "        passwords, or PINs.\n",
        "        \"\"\")\n",
        "\n",
        "    elif topic == \"Password Security\":\n",
        "        st.write(\"\"\"\n",
        "        Online banking users should use strong, unique passwords and avoid reusing passwords across accounts.\n",
        "        \"\"\")\n",
        "\n",
        "    elif topic == \"Multi-Factor Authentication\":\n",
        "        st.write(\"\"\"\n",
        "        Multi-Factor Authentication strengthens account security by requiring more than one method of verification.\n",
        "        \"\"\")\n",
        "\n",
        "    elif topic == \"Safe Online Banking Behaviour\":\n",
        "        st.write(\"\"\"\n",
        "        Safe online banking behaviour includes avoiding public Wi-Fi, updating banking apps,\n",
        "        verifying website authenticity, and monitoring security alerts.\n",
        "        \"\"\")\n",
        "\n",
        "    elif topic == \"Biometric Authentication\":\n",
        "        st.write(\"\"\"\n",
        "        Biometric authentication uses unique physical characteristics such as fingerprints or facial recognition.\n",
        "        Users should understand how biometric data is stored, protected, and used.\n",
        "        \"\"\")\n",
        "\n",
        "    elif topic == \"AI Scams and Deepfake Fraud\":\n",
        "        st.write(\"\"\"\n",
        "        AI-generated scams and deepfake fraud can imitate real voices, images, or messages.\n",
        "        Users should verify urgent financial requests through official banking channels.\n",
        "        \"\"\")"
      ]
    }
  ]
}